### PR TITLE
Use `ctx.request.files` instead of `ctx.request.body.files` (#75)

### LINKED ISSUE #75: Big security vulnerability
Hi,

I've just realised that it is very easy to create a big security vulnerability when using this package to upload files (I almost did this on my site).

Suppose you have JSON body parsing enabled on a POST or PUT route, say '/upload-files', as well as multipart parsing. This is quite easy to do e.g. if you add JSON parsing as global middleware. Suppose it expects the files to be in a field named 'uploads'. Then you can make a POST or PUT request to '/upload-files' with a JSON body that looks something like `{"files": {"uploads": [{"path": "/any/file/path"}]}}`, making the request handler think a file has been uploaded to `/any/file/path`. Now suppose that the handler is set up to copy uploaded files into a public uploads folder. By choosing the path appropriately I can make the server copy any file I like on the server into the public uploads folder and then view its contents. So by using well-known paths of sensitive files I can read private keys, passwords etc. and maybe even gain full access to the server this way.

I haven't tried actually doing this, but I think it's correct (sorry if I'm wrong). In my opinion, it would be better to put the files object on ctx.request instead of ctx.request.body, so that we know it can be trusted.

Thanks.

### PR DESCRIPTION
**Pull request by MarkHerhold**
This is an extension of #77 by @imkimchi, which fixes #75 with some changes:

- The overall approach from the original PR was kept, which moves `files` out of Node.js and Koa's `body` object
- A test endpoint for echoing text was added so the `/users` test endpoint didn't have two different jobs
- Some tests were simplified
- All tests are now passing
- README updated

**Proposed package changes:**
- publish a new version of the 1.x branch as `3.0.0` to npm
- publish a new version of the 2.x branch as `4.0.0` to npm
- mark all prior versions of `koa-body` as deprecated with a link to issue #75

I look forward to feedback on this.

### CODE REVIEW

**Comment by MarkHerhold** [comment]
pinging @VictorMMG @IlyaSemenov @damianb @imkimchi @dlau for comments 👋

**Comment by IlyaSemenov** [comment]
To be honest I don't like `ctx.request.body.fields`. This makes route handlers unnecessarily fragile:

1) If someones changes `<form` to `<form enctype="multipart/form-data">`, the data (input fields) on server will go to a different variable, and handlers will break until manually adjusted.

2) If you use `const user = ctx.request.body.fields || ctx.request.body` hack (like in the test case), and someone adds `<input name="field">`, the handlers will break again. How good is that?

Both problems will be non-existent if the middleware was **always** putting fields into `ctx.request.body`. Since we're in any case introducing a backwards-incompatible change, why don't go further and shoot two birds?

Which problem do you try to solve by going with `Obect.assign` over `ctx.req.body` instead of simple assignment? Is there a case when body will have anything else useful besides `fields`?

**Comment by damianb** [comment]
Seconding @IlyaSemenov on that.  Having the odd split between `ctx.request.body.fields`, depending on content type, makes this a seriously fragile situation for anyone reliant on the middleware.  Depending on the form's content type, your desired input changes location, making things programmatically unstable.  While sure, you could tell anyone that X has to be multipart, and Y must not be, that should *not be necessary* as it adds useless, unneeded complexity and confusion.

The use of the hack that @IlyaSemenov mentions, `const user = ctx.request.body.fields || ctx.request.body` is a sign that we have not made our data structure predictable.  It really, really needs to go.

**Comment by MarkHerhold** [comment]
@damianb @IlyaSemenov Thanks for your input. Please see my changes.

**Comment by damianb** [comment]
Looks fine to me. Nothing else to add.

**Pull request merged**
