### PR TITLE
Removing patchNode, patchKoa options

### PR DESCRIPTION
**Pull request by MarkHerhold**
Removing the patchNode and patchKoa options.

As part of the next major release, addresses https://github.com/dlau/koa-body/issues/139#issuecomment-480223780

Ping @damianb to review.

### CODE REVIEW

**Comment by damianb** [comment]
Looks okay.

Question - should we or should we not also do something along the lines of `ctx.request.body = {}` at the very beginning of the middleware lifecycle?  That way we can remove the undefined union typing of `ctx.request.body` and leave it entirely as `any`.  (`ctx.request.files` is perfectly fine to still have typed as `Files | undefined`.)

**Comment by damianb** [comment]
Also, *potentially* related to #144 as a result.  Could address that root issue if we consider the bit in the prior comment.

**Comment by damianb** [comment]
Definitely thinking now that a follow up PR should handle setting `ctx.request.body` consistently and also look into addressing #115 simultaneously.

I'm okay with merging it.

**Comment by MarkHerhold** [comment]
I'm OK with type changes in v5 but I think we should do this in another PR and attempt to be type-compatible with koa-body's type definition, [which now appears to be `any`](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f7d88a7099f407a449bb210a4c36fecbdc0454ff#diff-ef40de4f9d2066a6958dad2f45451f3a).

**Pull request merged**
