### PR TITLE
Shorten syntax on catch

### PR DESCRIPTION
**Pull request by dlau**
Following up on #41 - 

* Clean up some whitespace
* Shorten the overall try catch

Opinions/objections?

### CODE REVIEW

**Comment by unDemian** [comment]
Honestly I'm fine with how things are.
`if (!opts.onError) throw parsingError;
         opts.onError(parsingError, this);`
I don't like this version because the user can send stuff like onError = {} and it will throw an error.
Now about the brackets I see there are a lot of opinionated people. I invite them to create a PR with less lines.

**Comment by tunnckoCore** [comment]
That's just [enough](https://github.com/tunnckoCore/koa-better-body/blob/master/utils.js#L80-L96). Then just one if check would work.

**Comment by unDemian** [comment]
@tunnckoCore You are trying to optimize the use of brackets but you have 2 conditionals. One for checking the type then one for checking the true / false value. I did that with one check.

I don't really have time for this. If you like that short catch so much please push the code here. I tried helping but I really don't have time for this kind of "conflicts".

Have a great day

**Comment by tunnckoCore** [comment]
I don't have problems, it's not my package anymore. I have more stable and older package, with much more features and great code.

> One for checking the type then one for checking the true / false value.

I just want to allow users to not have problems if `onError` or `onerror` is given. In anyway, i don't think it is needed et al, because koa has `onerror`.

**Pull request closed without merging**
