### PR TITLE
Add flags for all upload types

### PR DESCRIPTION
**Pull request by unDemian**
Parsing url encoded file uploads does not work properly. Could not figure out the exact issue so I had to switch to another parser for that part. 

I added flags for enable/disable all types of parsing. This adds some more flexibility to the package.

Nice work.
Thanks

### CODE REVIEW

**Comment by dlau** [comment]
Looks great

Could you merge/rebase your branch to the latest version of master for ci?

Thank you!

**Comment by dlau** [comment]
#37

**Comment by tunnckoCore** [comment]
What means "does not work properly"? Some some errors, stack trace? Some case, code example, etc? I believe that it is just not used correctly.

**Comment by unDemian** [comment]
Hey, I was caught with work. I will post an example as soon as possible. The error appears whenever I try to parse url encoded files. Try using curl with --data-binary there were no errors but the uploaded file had a different md5 that the one that I sent via curl. I had no time to investigate further.

**Comment by dlau** [comment]
A repro case would be great as far as the (I assume `co-body`) bug is.

I merged it either way, adding additional flags to limit the scope of what this middleware does is in line with the original philosophy--a lightweight, non batteries included, wrapper around existing body parsers.

**Pull request closed without merging**
