### PR TITLE
support all text content types

### LINKED ISSUE #165: Support more text type like text/xml
## Problem/Feature Request Summary

Support more text type.

Now only support request content-type `text`.

And `text/plain`, `text/xml` need to be parsed to text.

### PR DESCRIPTION
**Pull request by MarkHerhold**
Adds support for all [text content types](https://www.iana.org/assignments/media-types/media-types.xhtml#text) by @ldarren.

Supersedes https://github.com/dlau/koa-body/pull/178 by @ldarren because I was unable to push changes to that repo.
FYI @wuteng606 @zzdhidden

Resolves #165

### CODE REVIEW

**Comment by MarkHerhold** [comment]
@ldarren would you mind providing an example use-case/implementation for the README? I'm guessing XML parsing?

**Comment by ldarren** [comment]
@MarkHerhold example added

**Comment by MarkHerhold** [comment]
@ldarren thank you, I'll grab that commit

**Comment by MarkHerhold** [comment]
Released in v4.2.0

**Pull request merged**
